---
# tasks file for roles/app

- name: Run BACKEND
  docker_container:
    name: my-api
    image: "chelsiels/tp-devops-simple-api:backend"
    networks:
      - name: my-network

- name: Run FRONTEND
  docker_container:
    name: frontend
    image: "chelsiels/tp-devops-simple-api:frontend"
    state: started
    networks:
      - name: my-network
    ports:
      - "8080:80"