---
# tasks file for roles/proxy

- name: Run HTTPD
  docker_container:
    name: httpd
    image: "chelsiels/tp-devops-simple-api:httpd"
    pull: always
    networks:
      - name: my-network
    ports:
      - "80:80"