name: Ansible Test
on:
  # To begin you want to launch this job in main and develop
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test-ansible: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      - name: Test inventory with the ping command
        working-directory: ansible
        run: ansible all -i inventories/setup.yml -m ping
