name: CI DevOps 2024
on:
  # To begin you want to launch this job in main and develop
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3

      # Finally build your app with the latest command
      - name: Build and test with Maven
        run: mvn clean verify

